name: Test and deploy

on:
  push:
    branches:
      - master

jobs:
  test_deploy:
    name: test and deploy Y-BuildKite-Monitor
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '16'
      - name: yarn install
        run: |
          yarn install
      - name: build project
        run: |
          yarn build
      - name: deploy to github pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: lyh1112@gmail.com
          build_dir: dist
